### ISSUE TITLE
Error while running model

### ISSUE THREAD

**Issue by RamolaShishupal** [ThibHlln/smartpy#1]
sm.set_parameters_with_dict(
AttributeError: 'SMART' object has no attribute 'set_parameters_with_dict'

i am trying to run this model but can't get output so how to fix this plz let me know

**Comment by ThibHlln** [comment]
Hi @RamolaShishupal,

Thank you for your interest in using SMARTpy, and for reporting this problem.

There is indeed a mistake in the [notebook example](https://github.com/ThibHlln/smartpy/blob/master/examples/api_usage_example.ipynb), it should read as:
```python
sm.parameters.set_parameters_with_dict(
    {
        'T': 1.0,
        'C': 1.0,
        'H': 0.20845,
        'D': 0.24606,
        'S': 0.0001230,
        'Z': 105.26,
        'SK': 46.82,
        'FK': 315.55,
        'GK': 1066.73,
        'RK': 10.64
    }
)
```

i.e. `set_parameters_with_dict` is a method of the object `Parameters` not of the object `SMART` directly.

Apologies for the inconvenience, I will modify the notebook once you've confirmed this solved this issue.

**Comment by RamolaShishupal** [comment]
hi it works man thanks
and u people have made a very nice model for runoff so we can use that
thank you so much and it works perfectly
thank u once again
