### ISSUE TITLE
is grpc call possible in smartpy

### ISSUE THREAD

**Issue by KamranShahid** [ThibHlln/smartpy#6]
is grpc call possible in smartpy.
i were searching a lot but didn't find anything. so thought i will ask it here

**Comment by ThibHlln** [comment]
Hi @KamranShahid,

No, I am afraid there is no support for gRPC.

You may want to have a look at the eWaterCycle initiative (https://github.com/eWaterCycle/ewatercycle), they rely on gRPC and MARRMoT, giving you access to the SMAR model (which the SMART model evolved from).

Hope this helps,
T
